src/app/main/forms.py
"""

app/main/forms.py

written by: Oliver Cordes 2021-02-17
changed by: Oliver Cordes 2021-02-22

"""


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, \
                    SubmitField, TextAreaField, SelectField, SelectMultipleField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length
from app.models import User, WhitelistGroup

from wtforms import widgets, SelectMultipleField

class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class WhitelistGroupForm(FlaskForm):
    groupname = StringField('Groupname', validators=[DataRequired()])
    role      = SelectField(coerce=int)

    submit = SubmitField('Add')

    def validate_groupname(self, groupname):
        group = WhitelistGroup.query.filter_by(groupname=groupname.data).first()
        if group is not None:
            raise ValidationError('Please use a different group name.')


class DeleteWhitelistGroupForm(FlaskForm):
    remove = SubmitField('Delete')


class AddUserForm(FlaskForm):
    group = SelectField(coerce=int)
    users = TextAreaField(u'User IDs')
    submit = SubmitField('Add')
    
class DeleteWhitelistUserForm(FlaskForm):
    group = SelectField(coerce=int)
    select = SubmitField('Select')
    remove = SubmitField('Delete')

src/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

src/app/main/routes.py
# -*- coding: utf-8 -*-
"""

app/main/routes.py
~~~~~~~~~~~~~~~~~~

written by : Oliver Cordes 2021-02-12
changed by : Oliver Cordes 2021-02-24

"""

import os
from datetime import datetime, timedelta
from dateutil.relativedelta import *
import pkg_resources

from flask import current_app, request, render_template, url_for, flash,  \
    redirect, send_from_directory, jsonify, session, make_response
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse, url_unparse

from flask_paginate import Pagination, get_page_parameter

from app import db
from app.main import bp
from app.models import *
from app.main.forms import WhitelistGroupForm, DeleteWhitelistGroupForm, \
    AddUserForm, DeleteWhitelistUserForm

from app.auth.admin import admin_required


APP_ROOT = os.path.dirname(os.path.abspath(__file__))


"""
before_request will be executed before any page will be
rendered
"""
@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    installed_packages = [(d.project_name, d.version)
                          for d in pkg_resources.working_set][::-1]

    server_users = User.query.count()
    server_roles = Roles.query.count()
    whitelist_users = WhitelistUser.query.count()
    whitelist_groups = WhitelistGroup.query.count()
    return render_template('index.html',
                            installed_packages=installed_packages,
                            server_users=server_users,
                            server_roles=server_roles,
                            whitelist_users=whitelist_users,
                            whitelist_groups=whitelist_groups,
                            title='Dashboard'
                            )


@bp.route('/whiteusers', methods=['GET', 'POST'])
@login_required
def show_users():
    # extract the information from the request
    search = False
    q = request.args.get('q')
    if q:
        search = True
    page     = request.args.get(get_page_parameter(), type=int, default=1)
    groupid  = request.args.get('groupid', type=int, default=0)
    

    # get the form
    dform = DeleteWhitelistUserForm()

    # setup the group box
    if current_user.administrator:
        groups = WhitelistGroup.query.all()
        dform.group.choices = [(0, 'All')]
    else:
        # calculate the groups available for a specific role
        role_ids = [r.id for r in current_user.roles]
        groups = WhitelistGroup.query.filter(
            WhitelistGroup.role_id.in_(role_ids)).all()
        dform.group.choices = []
        dform.group.choices = [(0, 'All')]

    # add all other groups
    dform.group.choices += [(g.id, g.groupname) for g in groups]

    if dform.validate_on_submit():
        if dform.remove.data:
            # get a list of selected items
            selected_users = request.form.getlist("whitelistusers")
            if dform.group.data != 0:
                selected_group = WhitelistGroup.query.get(dform.group.data)
                to_remove_complete = False
            else:
                to_remove_complete = True
            for userid in selected_users:
                to_remove = to_remove_complete
                user = WhitelistUser.query.get(int(userid))
                if not to_remove:
                    user.roles.remove(selected_group)
                    if not user.roles:
                        to_remove = True

                if to_remove:
                    db.session.delete(user)
                #print(user)
                #print(to_remove)
            db.session.commit()
            return redirect(url_for('main.show_users'))

        # must be the group select button
        groupid = dform.group.data

        # reset the view to start from the beginning
        page = 1


    # select the previous selected group
    dform.group.data    = groupid

    # calculate the valid groupids
    if groupid == 0:
        groupids = [g.id for g in groups]
    else:
        groupids = [groupid]

    # calculate the number of valid users from WhiteListUserGroups
    max_users = WhiteListUserGroups.query.filter(WhiteListUserGroups.group_id.in_(groupids)).count()

    pagination = Pagination(page=page, total=max_users,
                            css_framework='bootstrap4',
                            href=url_for('main.show_users') +
                            '?page={}&groupid=%d' % groupid,
                            display_msg='(Displaying <b>{start}-{end}</b> of <b>{total}</b> Users)',
                            search=search, record_name='whitelist_users')

    # select only the users from the pagination setup
    #if groupid == 0:   # all groups
    #    users = WhitelistUser.query.paginate(
    #        page, pagination.per_page, error_out=False).items
    #else:
    #    #role_ids = [r.id for r in current_user.roles]
    #    #groups = WhitelistGroup.query.filter(
    #    #    WhitelistGroup.role_id.in_(role_ids)).all()
    #    #group = WhitelistGroup.query.get(id=groupid)
    #    group_ids = [groupid]
    #    usergroups = WhiteListUserGroups.query.filter(WhiteListUserGroups.group_id.in_(group_ids)).paginate(page, pagination.per_page, error_out=False).items
    #    #users = WhitelistUser.query.filter(WhitelistUser.)
    #    usergroupsids = [i.user_id for i in usergroups]
    #    print(usergroupsids)
    #    users = WhitelistUser.query.filter(WhitelistUser.id.in_(usergroupsids))

    # get the userids from the valid users, using the pagination settings
    usergroups = WhiteListUserGroups.query.filter(WhiteListUserGroups.group_id.in_(
        groupids)).paginate(page, pagination.per_page, error_out=False).items
    usergroupsids = [i.user_id for i in usergroups]
    #print(usergroupsids)
    users = WhitelistUser.query.filter(WhitelistUser.id.in_(usergroupsids))


    return render_template('main/users.html',
                            whitelistuser=users,
                            dform=dform,
                            pagination=pagination, 
                            groups=groups,
                            title='Whitelist Users')


@bp.route('/whitelistgroups', methods=['GET','POST'])
@login_required
@admin_required
def whitelistgroups():
    rform = WhitelistGroupForm()
    rform.role.choices = [(r.id, r.name) for r in Roles.query.all()]
    
    dform=DeleteWhitelistGroupForm()
    if dform.validate_on_submit():
        # get a list of selected items
        selected_groups = request.form.getlist("whitelistgroups")
        for groupid in selected_groups:
            group = WhitelistGroup.query.get(int(groupid))
            db.session.delete(group)
        db.session.commit()


    return render_template('main/whitelistgroups.html',
                            whitelistgroups=WhitelistGroup.query.all(),
                            Roles=Roles,
                            dform=dform,
                            rform=rform,
                            title='Whitelist Groups')

@bp.route('/whitelistgroups/add', methods=['POST'])
@login_required
@admin_required
def add_whitelistgroups():
    rform = WhitelistGroupForm()
    rform.role.choices = [(r.id, r.name) for r in Roles.query.all()]
    if rform.validate_on_submit():
        group = WhitelistGroup(groupname=rform.groupname.data)
        group.role_id = rform.role.data
        db.session.add(group)
        db.session.commit()
        return redirect(url_for('main.whitelistgroups'))
    # in the case of validation errors,
    # use the same page again!
    return render_template('main/whitelistgroups.html',
                            title='Whitelist Groups',
                            groups=WhitelistGroup.query.all(),
                            Roles=Roles,
                            rform=rform,
                            dform=DeleteWhitelistGroupForm())


@bp.route('/adduser', methods=['GET', 'POST'])
@login_required
def add_whitelistuser():
    form = AddUserForm()

    if current_user.administrator:
        groups = WhitelistGroup.query.all()
    else:
        # calculate the groups available for a specific role
        role_ids = [r.id for r in current_user.roles]
        groups = WhitelistGroup.query.filter(WhitelistGroup.role_id.in_(role_ids)).all()

    form.group.choices = [(g.id, g.groupname) for g in groups]

    if form.validate_on_submit():
        print('Add users')
        # textfield is string
        data = form.users.data.split('\n')
        # recompile the list of users regarding to the instructions
        new_data = []
        for line in data:
            line = line.strip()
            if line != '':
                s = line.split(',')
                for i in s:
                    new_data.append(i.strip())

        group = WhitelistGroup.query.get(form.group.data)
        for username in new_data:
            whitelist_user = WhitelistUser.query.filter_by(username=username).first()
            if whitelist_user is None:
                whitelist_user = WhitelistUser(username=username)
                whitelist_user.comment = ''
                db.session.add(whitelist_user)
            whitelist_user.roles.append(group)
            db.session.commit()

        return redirect(url_for('main.show_users'))

    return render_template('main/add_user.html',
                            title='Add Whitelist User',
                            form=form,
                            groups=groups)


@bp.route('/uploaduser/<groupid>', methods=['POST'])
@login_required
def upload_whitelistuser(groupid):

    # get the file from the request
    f = request.files["file"]

    # split the lines from the submitted file
    for i in f:
        print(i.decode('utf8').strip())

    print(groupid)

    msg = 'User added'
    res = make_response(jsonify({"message": msg}), 200)

    return res

src/app/templates/main/add_user.html
{% extends "users_base.html" %}

{% block app_content %}

<div class="card">
  <div class="card-header">
      <h5>Add user</h5>
  </div>
  <div class="card-body">
    <form id="add_list_user" class="form-horizontal mb-5" role="form" method="post" action="">
      {{form.hidden_tag()}}
      <div class="input-group form-group">
        <div class="input-group-prepend">
          <div class="input-group-text">
            Groups
          </div>
        </div>
        {{form.group(id="group", class_="form-control")}}
      </div>
      <div class="input-group form-group">
      {{form.users(class_="form-control", rows="10", title="Enter user IDs in multiple lines, all IDs in the same line needs to be comma seperated!", 
            data_placement="top", data_toggle="tooltip",
            placeholder="user IDs (comma seperated in the same line or IDs in multiple lines)")}}
      </div>
      {{form.submit(class_="btn btn-info") }}
    </form>
    
    <div class="input-group form-group">
      <h5>Upload a file with User IDs</h5>
    </div>

    <div class="input-group form-group mt-3">
      <div class="input-group-prepend">
        <div class="input-group-text">
          New file
        </div>
      </div>
      <div class="custom-file">
        <input type="file" class="custom-file-input" name="file_input" id="file_input" oninput="input_filename();"
          accept=".dat, .txt, .list">
        <label id="file_input_label" class="custom-file-label" for="image">Choose file with user IDs...</label>
        </div>
        <button onclick="upload('{{url_for('main.upload_whitelistuser',groupid='')}}');" id="upload_btn" class="btn btn-info">Upload</button>
        <button class="btn btn-primary d-none" id="loading_btn" type="button" disabled>
          <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
          Uploading...
        </button>
        <button type="button" id="cancel_btn" class="btn btn-secondary d-none">Cancel upload</button>
      </div>
    </div>
    <div id="progress_wrapper" class="d-none">
      <label id="progress_status"></label>
      <div class="progress mb-3">
        <div id="progress" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
    </div>
    <div id="alert_wrapper"></div>
    </div>
</div>


{% endblock %}

{% block scripts %}
{{super()}}

<script>
function doStuff(){
  return (confirm('Do you really want to remove these items?'))
}
</script>

<!-- Functionality of upload process -->
<script>

// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function () {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});


// javascript code for upload files
// Get a reference to the progress bar, wrapper & status label
var progress = document.getElementById("progress");
var progress_wrapper = document.getElementById("progress_wrapper");
var progress_status = document.getElementById("progress_status");


// Get a reference to the 3 buttons
var upload_btn = document.getElementById("upload_btn");
var loading_btn = document.getElementById("loading_btn");
var cancel_btn = document.getElementById("cancel_btn");

// Get a reference to the alert wrapper
var alert_wrapper = document.getElementById("alert_wrapper");

// Get a reference to the file input element & input label
var input = document.getElementById("file_input");
var file_input_label = document.getElementById("file_input_label");

// Get a reference to the group selector
var group_selector = document.getElementById("group");

// Function to show alerts
function show_alert(message, alert) {

    alert_wrapper.innerHTML = `
    <div id="alert" class="alert alert-${alert} alert-dismissible fade show" role="alert">
      <span>${message}</span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  `
}


// Function to upload file
function upload(url) {

  // Reject if the file input is empty & throw alert
  if (!input.value) {

    show_alert("No file selected", "warning")

    return;

  }

  // get the group id from the selector widet 
  var group_id = group_selector.value;
  // the url has a / at the end, because of url_for() in
  // python and a reference with a group_id at the end 
  // which is unknown during jinja2 processing and html
  // setup
  var group_url = url + group_id;

  // Create a new FormData instance
  var data = new FormData();
  
  // Create a XMLHTTPRequest instance
  var request = new XMLHttpRequest();
  
  // Set the response type
  request.responseType = "json";
  
  // Clear any existing alerts
  alert_wrapper.innerHTML = "";
  
  // Disable the input during upload
  input.disabled = true;
  
  // Hide the upload button
  upload_btn.classList.add("d-none");

  // Show the loading button
  loading_btn.classList.remove("d-none");
  
  // Show the cancel button
  cancel_btn.classList.remove("d-none");
  
  // Show the progress bar
  progress_wrapper.classList.remove("d-none");
  
  progress.setAttribute("style", `width: 0%`);
  progress.setAttribute("aria-valuenow",`0`);
  
  // Get a reference to the file
  var file = input.files[0];
  
  // Get a reference to the filename
  var filename = file.name;
  
  // Get a reference to the filesize & set a cookie
  var filesize = file.size;
  document.cookie = `filesize=${filesize}`;

  // Append the file to the FormData instance
  data.append("file", file);
  
  // request progress handler
  request.upload.addEventListener("progress", function (e) {
  
    // Get the loaded amount and total filesize (bytes)
    var loaded = e.loaded;
    var total = e.total
  
    // Calculate percent uploaded
    var percent_complete = (loaded / total) * 100;
  
    // Update the progress text and progress bar
    progress.setAttribute("style", `width: ${Math.floor(percent_complete)}%`);
    progress.setAttribute("aria-valuenow", `${Math.floor(percent_complete)}`);
    progress_status.innerText = `${Math.floor(percent_complete)}% uploaded`;
  
  })

  // request load handler (transfer complete)
  request.addEventListener("load", function (e) {
  
    if (request.status == 200) {
  
      show_alert(`${request.response.message}`, "success");
  
  
      // timeout without function wrapper is not workin in Chrome!
      setTimeout(function(){
      //banner_change(this);
        location.reload();
      }, 3000);
    }
    else {
  
      show_alert(`Error uploading file`, "danger");
  
    }
  
    reset();
  
  });

  // request error handler
  request.addEventListener("error", function (e) {
  
    reset();
  
    show_alert(`Error uploading file`, "warning");
  
  });
  
  // request abort handler
  request.addEventListener("abort", function (e) {
  
    reset();
  
    show_alert(`Upload cancelled`, "primary");
  
  });

  // Open and send the request
  request.open("post", group_url);
  request.send(data);
  
  cancel_btn.addEventListener("click", function () {
  
    request.abort();
  
  })
  
}

// Function to update the input placeholder
function input_filename() {

  file_input_label.innerText = input.files[0].name;

}


// Function to reset the page
function reset() {

  // Clear the input
  input.value = null;

  // Hide the cancel button
  cancel_btn.classList.add("d-none");

  // Reset the input element
  input.disabled = false;

  // Show the upload button
  upload_btn.classList.remove("d-none");

  // Hide the loading button
  loading_btn.classList.add("d-none");

  // Hide the progress bar
  progress_wrapper.classList.add("d-none");

  // Reset the progress bar state
  //progress.setAttribute("style", `width: 0%`);
  //progress.setAttribute("aria-valuenow",`0`);

  // Reset the input placeholder
  file_input_label.innerText = "Select file";

}

</script>



{% endblock %}

src/app/templates/main/users.html
{% extends "users_base.html" %}


{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='pagination.css')}}">
{% endblock %}


{% block app_content %}

<div class="card">
    <div class="card-header">
        <h5>List of available whitelist-users</h5>
    </div>
    <div class="card-body">
        <form id="rolesformdelete" class="form-horizontal mb-5" role="form" method="post" action="">
            {{dform.hidden_tag()}}
            <div class="input-group form-group col-6">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        Groups
                    </div>
                </div>
                <div class="input-group-text">
                    {{dform.group(id="group", class_="form-control")}}
                </div>
                <div class="input-group-text">
                    {{dform.select(class_="btn btn-info")}}
                </div>
            </div>
            <div class="table-responsive col-6">
                {{ pagination.links }}
                <table class="table table-sm table-bordered">
                    <thead>
                        <td></td>
                        <td>ID</td>
                        <td>Name</td>
                        <td>Group</td>
                        <td>Time stamp</td>
                    </thead>
                    {% for user in whitelistuser %}
                    <tr>
                        <td>
                            <label>
                                <input type="checkbox" name="whitelistusers" value="{{user.id}}">
                            </label>
                        </td>
                        <td>{{user.id}}</td>
                        <td>{{user.username}}</td>
                        <td>{{user.group_str()}}</td>
                        <td>{{user.timestamp.strftime('%Y-%m-%d %H:%M:%S')}}</td>
                    </tr>
                    {% endfor %}
                </table>
                {{ pagination.info }}
                {{ pagination.links }}
            </div>
            <button onclick="checkall('whitelistusers')" id="btn-checkall" type="button" class="btn btn-info">
                    <i class="icon-hand-right"></i>Select all</button>
            <button onclick="uncheckall('whitelistusers')" id="btn-uncheckall" type="button" class="btn btn-info">
                    <i class="icon-hand-right"></i>Unselect all</button>
            {{ dform.remove(onclick="return (ask_for_deletion())", class_="btn btn-danger") }}

        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{super()}}

<script>
    function checkall(name) {
            var x = document.getElementsByName(name);
            var i;
            for (i = 0; i < x.length; i++) {
                if (x[i].type == "checkbox") {
                    x[i].checked = true;
                }
            }
        }

        function uncheckall(name) {
            var x = document.getElementsByName(name);
            var i;
            for (i = 0; i < x.length; i++) {
                if (x[i].type == "checkbox") {
                    x[i].checked = false;
                }
            }
        }
</script>

{% endblock %}

src/app/templates/main/whitelistgroups.html
{% extends "users_base.html" %}

{% block app_content %}

<div class="card">
  <div class="card-header">
      <h5>List of available whitelist-groups</h5>
  </div>
  <div class="card-body">
    <form id="rolesformdelete" class="form-horizontal mb-5" role="form" method="post" action="">
      {{dform.hidden_tag()}}
      <div class="table-responsive col-6">
        <table class="table table-bordered">
          <thead>
            <td></td>
            <td>ID</td>
            <td>Group name</td>
            <td>Associated role</td>
            <td>Time stamp</td>
          </thead>
          {% for group in whitelistgroups %}
          <tr>
            <td>
              <label>
                <input type="checkbox" name="whitelistgroups" value="{{group.id}}">
              </label>
            </td>
            <td>{{group.id}}</td>
            <td>{{group.groupname}}</td>
            <td>{{Roles.query.get(group.role_id).name}}</td>
            <td>{{group.timestamp.strftime('%Y-%m-%d %H:%M:%S')}}</td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {{ dform.remove(onclick="return (ask_for_deletion())", class_="btn btn-danger") }}
    </form>
    <div>
    </div>
    <form id="rolesformadd" class="form-horizontal" role="form" method="post" action="{{url_for('main.add_whitelistgroups')}}">
      {{rform.hidden_tag()}}
      {% if rform.groupname.errors|length > 0 %}
      <div id="signupalert" class="alert alert-danger">
        {% for error in rform.groupname.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% endif %}
      <div class="input-group form-group">
          <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-users"></i></span>
          </div>
          {{rform.groupname(id="groupname", class_="form-control", placeholder="group name" ) }}
      </div>
      <div class="input-group form-group">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-user-tag"></i></span>
        </div>
        {{rform.role(id="role", class_="form-control")}}
      </div>
      {{ rform.submit(class_="btn btn-info") }}
    </form>
  </div>
</div>

{% endblock %}